version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/dollarshaveclub/guardian
    steps:
      - checkout
      - run: go test -v ./pkg/...